version: '3.8'
services:
  database:
    image: postgres:12.3-alpine
    container_name: app_database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/data/db:/var/lib/postgresql/data
  
  database_test:
    image: postgres:12.3-alpine
    container_name: app_database_test
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db_test
    ports:
      - "5433:5432"